import { Document, Page, StyleSheet, Text, View } from '@react-pdf/renderer';
import type { ItineraryResult } from '../types';
import { WAKING_HOURS_PER_DAY, formatHours, formatMin } from '../lib/calc';

const styles = StyleSheet.create({
  page: { padding: 48, fontSize: 11, fontFamily: 'Helvetica', color: '#1e293b' },
  title: { fontSize: 22, fontFamily: 'Helvetica-Bold', marginBottom: 4 },
  subtitle: { fontSize: 12, color: '#64748b', marginBottom: 24 },
  row: { flexDirection: 'row', borderBottomWidth: 1, borderBottomColor: '#e2e8f0', paddingVertical: 7 },
  headerRow: { borderBottomWidth: 2, borderBottomColor: '#94a3b8' },
  totalRow: { borderBottomWidth: 0, borderTopWidth: 2, borderTopColor: '#94a3b8', marginTop: 2 },
  bold: { fontFamily: 'Helvetica-Bold' },
  city: { flex: 3 },
  daytripCity: { color: '#64748b' },
  num: { flex: 1, textAlign: 'right' },
  footer: { position: 'absolute', bottom: 32, left: 48, right: 48, fontSize: 8, color: '#94a3b8' },
});

/** Stays with their day trips attached, in itinerary order. */
function groupDayTrips(result: ItineraryResult) {
  const groups: { base: ItineraryResult['perCity'][number]; trips: ItineraryResult['perCity'] }[] = [];
  for (const c of result.perCity) {
    if (c.kind === 'daytrip' && groups.length > 0) groups[groups.length - 1].trips.push(c);
    else groups.push({ base: c, trips: [] });
  }
  return groups;
}

export function ItineraryPdf({ result }: { result: ItineraryResult }) {
  const route = groupDayTrips(result)
    .map((g) =>
      g.trips.length
        ? `${g.base.cityName} (+ ${g.trips.map((t) => t.cityName).join(', ')})`
        : g.base.cityName,
    )
    .join(' → ');

  return (
    <Document title="TripSense itinerary" author="TripSense">
      <Page size="A4" style={styles.page}>
        <Text style={styles.title}>TripSense — Your real time budget</Text>
        <Text style={styles.subtitle}>{route}</Text>

        <View style={[styles.row, styles.headerRow]}>
          <Text style={[styles.city, styles.bold]}>Destination</Text>
          <Text style={[styles.num, styles.bold]}>Nights</Text>
          <Text style={[styles.num, styles.bold]}>Transit in</Text>
          <Text style={[styles.num, styles.bold]}>Waking hours</Text>
          <Text style={[styles.num, styles.bold]}>Full days</Text>
        </View>

        {result.perCity.map((c, i) => {
          const daytrip = c.kind === 'daytrip';
          return (
            <View key={`${c.cityId}-${i}`} style={styles.row}>
              <Text style={daytrip ? [styles.city, styles.daytripCity] : styles.city}>
                {daytrip ? `    ↳ ${c.cityName} (day trip)` : c.cityName}
              </Text>
              <Text style={styles.num}>{daytrip ? '—' : c.nights}</Text>
              <Text style={styles.num}>
                {c.transitInMin > 0 ? `${formatMin(c.transitInMin)}${daytrip ? ' rt' : ''}` : '—'}
              </Text>
              <Text style={styles.num}>{formatHours(c.wakingHours)}</Text>
              <Text style={styles.num}>{c.equivalentDays.toFixed(2)}</Text>
            </View>
          );
        })}

        <View style={[styles.row, styles.totalRow]}>
          <Text style={[styles.city, styles.bold]}>Total</Text>
          <Text style={[styles.num, styles.bold]}>{result.totalNights}</Text>
          <Text style={[styles.num, styles.bold]}>{formatMin(result.totalTransitMin)}</Text>
          <Text style={[styles.num, styles.bold]}>{formatHours(result.totalWakingHours)}</Text>
          <Text style={[styles.num, styles.bold]}>
            {(result.totalWakingHours / WAKING_HOURS_PER_DAY).toFixed(2)}
          </Text>
        </View>

        <Text style={styles.footer}>
          Waking hours = nights × {WAKING_HOURS_PER_DAY}h − transit into the city, assuming 8h sleep
          per night. Day trips ("rt" = round-trip transit) spend their base city's hours; nights stay
          with the base. Travel times are typical-schedule estimates including door-to-door overhead,
          not guarantees. Generated by maketripsense.com — data via open European GTFS feeds
          (Transitous), DB, ÖBB, SNCF, Eurostar, Trenitalia and others.
        </Text>
      </Page>
    </Document>
  );
}
